queue_rules:
  - name: default
    conditions:
      - "check-success=Check terraform / terraform-check"
      - "check-success=Lambda test / test"
pull_request_rules:
  - name: automatic merge for Scala Steward
    conditions:
      - author=tna-digital-archiving-jenkins
      - "check-success=Check terraform / terraform-check"
      - "check-success=Lambda test / test"
      - or:
          - files=build.sbt
          - files~=^(!?project/)
    actions:
      review:
        type: APPROVE
        message: Automatically approving Scala Steward updates
      queue:
        name: default
